### PR TITLE
Improve ketos transcribe user interface

### PR DESCRIPTION
**Pull request by Gijsjan**
* remove dependency on jQuery and use vanilla JS
* include JS from file
* keep active line highlighted when transcribing
* differentiate between hover and active line
* make lines scrollable to be able to align with facsimile
* show line numbers
* fix localStorage
* use < button > element for download

### CODE REVIEW

**Comment by mrocr** [comment]
@Gijsjan Have you fixed the fail checks?

**Comment by Gijsjan** [comment]
I'm sorry, the Travis output is Greek to me. There seems to be an import failure, but I can't find any tests failing. I could try to replicate the Travis config, but I'm on a holiday until September, therefor it will have to wait.

**Comment by mittagessen** [comment]
Sorry for the delayed response I've been on vacation for the last few weeks. The CI failure is unrelated to your changes but caused by some wonkery with the pytorch installation in the CI environment. I can merge these changes although the integration of the new baseline segmenter will require a different transcription interface in the future.

**Comment by mrocr** [comment]
@mittagessen close the pull, in-favor of escriptorium-like integration
@Gijsjan Thank you for your contribution, I'd recommend having a look a [escriptorium](https://gitlab.inria.fr/scripta/escriptorium), since kraken is moving towards base-line segmentation methods.

**Pull request merged**
