### PR TITLE
Shapely 2.0/1.8.4 compatibility

### PR DESCRIPTION
**Pull request by mittagessen**
Various fixes to both adapt kraken to the API changes coming with shapely 2.0 but also deal with implicit behavioral changes (most from newer versions of the underlying GEOM library).

### CODE REVIEW

**Comment by bertsky** [comment]
@mittagessen despite this, `install_requires` still contains `shapely==1.8.5` right up to master:
https://github.com/mittagessen/kraken/blob/dd846ef32b1816e423c5741498d81f38a5e8fb73/setup.cfg#L59

Is this intentional?

**Comment by mittagessen** [comment]
There's a behavior change in 2.0 causing broken line bounding polygons that we haven't had time to track down. So we downgraded back to 1.8.5. IIRC it was somewhere in the region of interest computation code which uses a mix of analytical and numerical methods which can be somewhat fragile, especially as the underlying GEOM library's behavior can change quite significantly between versions.

**Comment by bertsky** [comment]
I know, it's a PITA. Ok, so this _is_ intentional – it looked as if this PR was already sufficient.

FYI, they also piggy-backed changing from `.type` to `.geom_type` but forgot to mention it in their migration guide.

BTW, have you ever been hit by segfaults from [shapely vs torch import order](https://github.com/shapely/shapely/issues/1598)? In kraken.blla you import torch before shapely – is that a coincidence or deliberate?

**Comment by mittagessen** [comment]
> FYI, they also piggy-backed changing from .type to .geom_type but forgot to mention it in their migration guide.

Yeah, we did all the interface adaptations, there is just a numerical difference somewhere that sometimes results in worse bounding polygons with 2.0 than 1.8.x. Hence pinning back to 1.8.5. I hope to replace the whole polygonizer in the mid-term and get rid of shapely completely.

> BTW, have you ever been hit by segfaults from https://github.com/shapely/shapely/issues/1598? In kraken.blla you import torch before shapely – is that a coincidence or deliberate?

Nope. It's pure coincidence.

**Comment by bertsky** [comment]
> despite this, `install_requires` still contains `shapely==1.8.5` right up to master:
> 
> https://github.com/mittagessen/kraken/blob/dd846ef32b1816e423c5741498d81f38a5e8fb73/setup.cfg#L59

BTW, this version was [broken](https://github.com/shapely/shapely/issues/1567). Please specify 1.8.5.post1 or use `~=` instead of `==`.

**Comment by bertsky** [comment]
https://github.com/mittagessen/kraken/commit/a7062f0f7e59d626845fbd4ec5f28b955b5f849a – thanks!

If I had one more wish, it would be an additional release on PyPI including that fix (perhaps just a post-release i.e. 4.3.10.post1), so it works with pip installs on a dependency chain...

**Comment by bertsky** [comment]
> If I had one more wish, it would be an additional release on PyPI including that fix (perhaps just a post-release i.e. 4.3.10.post1), so it works with pip installs on a dependency chain...

@mittagessen I have to keep asking for this one as not only does it break Kraken but also our ocrd_all builds which include Kraken in the same venv to save space. Since Kraken uses pbr for builds and thus you need to have an annotated git tag to get a source install without ending up with version 0.0.0, a release on PyPI seems to be the only proper way out of this.

**Comment by mittagessen** [comment]
Ah sorry. I just tagged a new hotfix release.

**Comment by bertsky** [comment]
Thanks!

**Pull request merged**
