### PR TITLE
Allow bug fix releases of Python 3.10

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
@mittagessen, are you planning a 3.0.10 release, too? If yes, a similar change for that would also be useful, because that would enable OCR-D builds with Python 3.10.2.

**Comment by mittagessen** [comment]
Thanks. The last time I checked there was some dependeny that hadn't been packaged for 3.10 yet but kraken itself is compatible as far as I can tell.

I really don't want to do minor releases in the 3.0 version branch anymore but it might be necessary depending on how quickly we get to adapt escriptorium to the new training API. Are the OCR-D builds inference only? Then 4.x should definitely work out of the box. For training some adaptation is needed.

**Comment by stweil** [comment]
Thanks, then OCR-D should indeed update to use 4.x. I noticed that 4.0 stopped support for Python 3.6 which is still used by OCR-D. :-(

**Comment by mittagessen** [comment]
On 22/03/16 09:17AM, Stefan Weil wrote:
> Thanks, then OCR-D should indeed update to use 4.x. I noticed that 4.0 stopped support for Python 3.6 which is still used by OCR-D. :-(

I threw out 3.6 because security support ran out the end of last year
and some libraries like numpy have stopped 3.6 releases for the same
reason.

**Comment by stweil** [comment]
@mittagessen, could you please merge this PR to make a recent Python 3.10.2 work with kraken from Git master?

**Pull request merged**
