### PR TITLE
Applies segtrain hyper params fix to reco training.

### PR DESCRIPTION
**Pull request by lauxley**
+ Applies segtrain hyper params fix to reco training.
+ Some refacto
+ Adds  `nn.hyper_params = hyper_params` in recognition_train_gen, it wasn't there but maybe it's done somewhere else?

### CODE REVIEW

**Comment by mittagessen** [comment]
Thanks. The hyper_param dumping was fixed in another branch that I haven't merged, yet but with your refactoring I'm just going to merge this.

**Comment by lauxley** [comment]
I think it's mergeable, I only tested with a direct call to recognition_train_gen from scratch and on top of an existing model with a single dataset. So maybe just quickly check from the command line.

**Comment by lauxley** [comment]
Actually  the 'Maximum epochs reached' reached message is only shown in segmentation training. 
Would it be a good or terrible idea to make hyper parameters validation type thing?

**Comment by lauxley** [comment]
Coming back to this, fixed the message by moving it to a embryo of hyper parameters validation function.

I stumbled upon another issue by doing so, the `event_callback` passed to `KrakenTrainer.run()` is not called for epoch 0, it can be a problem especially if training on top of a model and the additional training doesn't improve `eval_res['val_metric']`.
Then `trainer.stopper.best_epoch` remains 0, so in eScriptorium we are trying to copy the model created at epoch 0 in the event_callback function which does not exist.

**Comment by sixtyfive** [comment]
Hi all! Just wanting to add a quick "me too" here, mostly because of eScript...

**Comment by mittagessen** [comment]
I'll deal with the last point separately. Let's merge this.

**Pull request merged**
