### PR TITLE
Allow newer versions for torch package (required for Python 3.11)

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
Python 3.11 is part of the new Debian stable (bookworm) and requires newer versions of torch. My first tests with this patch and kraken in eScriptorium did not show any obvious problems.

**Comment by mittagessen** [comment]
To not pin a maximum version is a bad idea as pytorch (or its dependencies) regularly break stuff. Could you change it to `>1.11,~=2.0.0`? Although I'm a bit suspicious about 3.11 support as coremltools still doesn't support it so I wonder what you've been actually installing...

**Comment by stweil** [comment]
Without any upper limit Python 3.9 and 3.11 install torch-2.0.1. `>1.11,~=2.0.0` can be simplified to `~=2.0.0`. Should I use that? It would also install torch-2.0.1 currently.

**Comment by stweil** [comment]
Meanwhile the pull request pins pytorch to 2.0.x.

**Comment by stweil** [comment]
Ping? It would help to have a newer kraken release with this fix available because more people start using the latest Debian stable with Python 3.11.

**Comment by mittagessen** [comment]
My apologies.

**Pull request merged**
