### PR TITLE
Use app dir storage instead of "POSIX".

### PR DESCRIPTION
**Pull request by QuLogic**
I'd prefer things to use the XDG standard. I'm not even sure that POSIX even defines this, so I'm not sure why the option is named that way.

### CODE REVIEW

**Comment by QuLogic** [comment]
Ping? (though it may need a rebase)

**Comment by mittagessen** [comment]
I personally prefer the traditional dotfiles approach, although I don't feel strongly about it either way. Is there any obvious benefit to the XDG specification?

**Comment by QuLogic** [comment]
It's simpler for users: `.config/<program>` instead of hundreds of `.<program>`. `click` does not really expose it all, but XDG directories provide a more segregated layout, e.g., cache data can go in `.cache/<program>` and users would be able to clean that up if they need space.

**Comment by QuLogic** [comment]
:question:

**Comment by mittagessen** [comment]
sorry for having the patch in limbo for so long.

**Pull request merged**
