### PR TITLE
Enhancement/add resize and fix a regression for union

### LINKED ISSUE #478: Are `add` and `both` synonym ?
From #476 

> Just a quick note: I am still quite unsatisfied on the naming scheme of codec merging. Specifically, add and both are quite synonym to me (add adds the new characters, both uses both set of character [while it actually only uses the new dataset vocabulary]). While it might be a breaking change, I would very much recommend moving to add and replace or something like this.
> To do something clean regarding both changing to something such as replace, we could allow both argument with a DeprecationWarning and map to replace

@dstoekl replied

> I support this and would support also the possibility to train excluding new characters. Something that would be clear and not break previous behavior could be:
> old_only
> new_only (corresponds to today's both)
> old_and_new (corresponds to today's add)

### PR DESCRIPTION
**Pull request by PonteIneptique**
This fixes #478 and #487.

I discovered a potential regression where the train_codec was not used to resize the output layer. This was causing #487 

I added some deprecation regarding #478. 

Test and docs are updated

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Here is the potential bug / regression found : 

https://github.com/mittagessen/kraken/pull/488/files#diff-974b9dde6ef2001d713a0eaaeb9bb2bd5f0f9c67e10eb1fb6d3aa1ccebee9701R519-R520

**Comment by mittagessen** [comment]
Yes, it's indeed a regression in the adaptation code.

**Comment by PonteIneptique** [comment]
There is a doubt in the test I "fixed" with my latest commit, see https://github.com/mittagessen/kraken/issues/487

I think it would be worth checking that I did not fix a test which should not have been fixed... (which has nothing to do with the regression ^^)

**Comment by mittagessen** [comment]
Could you rebase your branch on main? I can't pull the branch fast-forwardly to test your changes because it branched off from some earlier commit.

**Comment by PonteIneptique** [comment]
Should be good.

**Pull request merged**
