### PR TITLE
Added some tests to check that Arrows, XML, fine-tuning and codec work nicely together

### PR DESCRIPTION
**Pull request by PonteIneptique**
Hi there :)
We were tracking some bug the other day and we prepared some dummy dataset to track it. I thought it would be good to kinda propose integrated tests which checks for a suite of combination (Unicode normalization, Fine-Tuning, Arrows or XML).

I left the data to generate the arrow in case arrow change one day and we need to regenerate the arrows.

These checks a things a little different than `test_train.py`, so I hope you will see it as useful.

### CODE REVIEW

**Comment by mittagessen** [comment]
Thanks, I wanted to write some integration tests for the ptl modules but stopped after ending up with waay too many cases. It's a good start and I'll probably add some more in the future.

**Comment by PonteIneptique** [comment]
To do something clean regarding `both` changing to  something such as `replace`, we could allow both argument with a DeprecationWarning and map to `replace`

**Comment by dstoekl** [comment]
I support this and would support also the possibility to train excluding new characters. Something that would be clear and not break previous behavior could be:
old_only
new_only (corresponds to today's both)
old_and_new (corresponds to today's add)

**Comment by PonteIneptique** [comment]
Maybe we should open a specific issue for this ;) See https://github.com/mittagessen/kraken/issues/478

**Pull request merged**
